using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using netcoreauth.model;

namespace netcoreauth.api.DataStore
{
  public static class TrainDataStore
  {
    public static List<Train> TrainList = new List<Train>()
        {
            new Train { Id = 12345, TrainName = "Gitanjali", From = "Nagpur", Depart = "10:00", InBetweenStations = new List<string>{ "Ajni", "Wardha", "Pulgaon", "Badnera", "Shegaon", "Daund" }, InBetweenStationsTime = new List<string>{ "10:05", "11.09", "11.30", "12:40", "22:12", "22:58" }, To= "Pune", TotalHrs = "12:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 20 }, new Prediction { Class = "ac3", Accuracy = 50 } } },
            new Train { Id = 5678, TrainName = "Sampakranti Express", From = "Nagpur", Depart = "12:00", InBetweenStations = new List<string>{ "Ajni", "Sevagram", "DhamanGaon", "Egatpuri", "Kalyan", "Dadar" }, InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15", "13:30", "13:45" }, TotalHrs = "02:00", To= "Mumbai", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 10 }, new Prediction { Class = "ac3", Accuracy = 90 } } },
            new Train { Id = 22692, TrainName = "Bangalore Rajdhani", From = "Mumbai", Depart = "12:00", InBetweenStations = new List<string>{ "Pune Junction", "belgaum", "Davangere", "Kadur", "Tumkur" }, InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15", "13:30" }, To= "Bangalore", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 20 }, new Prediction { Class = "ac3", Accuracy = 60 } } },
            new Train { Id = 12622, TrainName = "TamilNadu Express", From = "Hyderabad", Depart = "12:00", InBetweenStations = new List<string>{ "Secundarabad", "Lingampalli", "Raichur", "Hindupur" }, InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15" }, To= "Bangalore", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 24 }, new Prediction { Class = "ac3", Accuracy = 20 } } },
            new Train { Id = 12722, TrainName = "Dakshin Express", From = "Hyderabad", Depart = "12:00", InBetweenStations = new List<string>{ "Begumpeth", "Zahirabad", "Latur", "Usmanabad", "Daund" }, InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15",  "13:30" },  To= "Pune", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 10 }, new Prediction { Class = "ac3", Accuracy = 40 } } },
            new Train { Id = 22416, TrainName = "A P Express", From = "Pune", Depart = "12:00",  InBetweenStations = new List<string>{ "Daund", "Kopargaon", "Shegaon", "Akola", "Pulgaon", "Ajni" }, InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15",  "13:30", "13:45" }, To= "Nagpur", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 60 }, new Prediction { Class = "ac3", Accuracy = 80 } } },
            new Train { Id = 12808, TrainName = "Samata Express", From = "Delhi", Depart = "12:00", InBetweenStations = new List<string>{ "Mathura", "Agra", "Gwalior", "Nagpur", "Balharshah", "Secundarabad" }, InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15",  "13:30", "13:45" }, To= "Hyderabad", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 30 }, new Prediction { Class = "ac3", Accuracy = 30 } } },
            new Train { Id = 12626, TrainName = "Kerala Express", From = "Nagpur", Depart = "12:00", InBetweenStations = new List<string>{ "Balharshah", "Warangel", "Tirupati", "Chittor", "Trivandram" }, InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15",  "13:30" }, To= "Kerala", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 80 }, new Prediction { Class = "ac3", Accuracy = 50 } } },
            new Train { Id = 12434, TrainName = "Chennai Rajdhani", From = "Pune", Depart = "12:00", InBetweenStations = new List<string>{ "Gulbarga", "Yadir", "Raichur", "Razampetha", "Perambur" },  InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15",  "13:30" },  To= "Chennai", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 100 }, new Prediction { Class = "ac3", Accuracy = 10 } } },
            new Train { Id = 12406, TrainName = "Gondwana Express", From = "Nagpur", Depart = "12:00", InBetweenStations = new List<string>{ "Ajni", "Wardha", "Shegaon", "Bhusawal", "Kopargaon", "Daund" },  InBetweenStationsTime = new List<string>{ "12:30", "12:45", "13:00", "13:15",  "13:30", "13:45" }, To= "Pune", TotalHrs = "02:00", Prediction = new List<Prediction>(){ new Prediction { Class = "sleeper", Accuracy = 50 }, new Prediction { Class = "ac3", Accuracy = 70 } } }
        };
  }
}
